on: [ push ]

name: Text UI Test

jobs:
  text_ui_test:
    name: Text UI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx
          architecture: x64
      - name: Run test
        working-directory: ${{ github.workspace }}/text-ui-test
        run: ./runtest.sh